// Script.js
ddia_novia_1_bcodeocument.addEventListener('DOMContentLoaded', función() {
    const matrixHearts = document.getElementById('matrixHearts');
        const heartSymbols = ['â ¤', 'â™¥', 'ðŸ'–', 'ðŸ'—', 'ðŸ'˜', 'ðŸ'“'];
            
                función createMatrixHearts() {
                        const corazón = document.createElement('div');
                                corazón.className = 'matriz-del-corazon';
                                        corazón.innerHTML = corazónSymbols[Math.floor(Math.random() * corazónSymbols.length)];
                                                corazón.estilo.izquierda = Math.random() * 100 + 'vw';
                                                        corazón.estilo.duraciónDeLaAnimación = 2 + Math.aleatorio() * 3 + 's';
                                                                corazón.estilo.opacidad = Math.random() * 0.5 + 0.3;
                                                                        corazón.estilo.tamañoDeFuente = 10 + Math.aleatorio() * 20 + 'px';
                                                                                matrixHearts.appendChild(corazón);
                                                                                        
                                                                                                establecerTiempo de espera(() => {
                                                                                                            corazón.remove();
                                                                                                                    }, 5000);
                                                                                                                        }
                                                                                                                            
                                                                                                                                setInterval(createMatrixHearts, 100);
                                                                                                                                    
                                                                                                                                        constante heartBtn = document.getElementById('heartBtn');
                                                                                                                                            const hiddenMessage = document.getElementById('mensajeoculto');
                                                                                                                                                
                                                                                                                                                    heartBtn.addEventListener('clic', función() {
                                                                                                                                                            hiddenMessage.style.display = 'bloque';
                                                                                                                                                                    para (sea i = 0; i < 30; i++) {
                                                                                                                                                                                establecerTiempo de espera(() => {
                                                                                                                                                                                                const x = Math.random() * ventana.ancho interno;
                                                                                                                                                                                                                const y = Math.random() * ventana.innerHeight;
                                                                                                                                                                                                                                crearExplosión(x, y);
                                                                                                                                                                                                                                            }, i * 50);
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                            función crearExplosión(x, y) {
                                                                                                                                                                                                                                                                    const explosion = document.createElement('div');
                                                                                                                                                                                                                                                                            explosión.innerHTML = heartSymbols[Math.floor(Math.random() * heartSymbols.length)];
                                                                                                                                                                                                                                                                                    explosion.style.position = 'fijo';
                                                                                                                                                                                                                                                                                            explosión.estilo.izquierda = x + 'px';
                                                                                                                                                                                                                                                                                                    explosión.style.top = y + 'px';
                                                                                                                                                                                                                                                                                                            explosión.estilo.color = `hsl(${Math.random() * 30 + 330}, 100%, 70%)`;
                                                                                                                                                                                                                                                                                                                    explosión.style.fontSize = '25px';
                                                                                                                                                                                                                                                                                                                            explosión.style.zIndex = '100';
                                                                                                                                                                                                                                                                                                                                    explosión.style.transform = 'escala(0)';
                                                                                                                                                                                                                                                                                                                                            explosion.style.animation = `pop 0,5 s hacia adelante, fadeOut 0,5 s 0,5 s hacia adelante`;
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                            documento.cuerpo.appendChild(explosión);
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                            establecerTiempo de espera(() => {
                                                                                                                                                                                                                                                                                                                                                                                        explosión.remove();
                                                                                                                                                                                                                                                                                                                                                                                                }, 1000);
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                            const estilo = document.createElement('estilo');
                                                                                                                                                                                                                                                                                                                                                                                                                estilo.textContent = `
                                                                                                                                                                                                                                                                                                                                                                                                                        @keyframes pop {
                                                                                                                                                                                                                                                                                                                                                                                                                                    para { transformar: escala(1) traducir(${Math.random() * 40 - 20}px, ${Math.random() * 40 - 20}px); }
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    @keyframes fadeOut {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                a { opacidad: 0; transformar: escala(0.5) traducir(${Math.random() * 100 - 50}px, ${Math.random() * 100 - 50}px); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                documento.head.appendChild(estilo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });